name: Build and Publish

on:
  push:
    tags:
      - '*'
      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build and Publish for Linux
        run: |
          dotnet publish -c Release -r linux-x64 --self-contained true --no-restore --exclude-source-files --exclude appsettings.Development.json
          mkdir -p artifacts/linux-x64
          mv ./bin/Release/net6.0/linux-x64/publish/* ./artifacts/linux-x64/

      - name: Build and Publish for Windows
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true --no-restore --exclude-source-files --exclude appsettings.Development.json
          mkdir -p artifacts/win-x64
          mv ./bin/Release/net6.0/win-x64/publish/* ./artifacts/win-x64/

      - name: Generate Release Notes
        id: release_notes
        run: |
          npm install -g conventional-changelog-cli
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          echo "::set-output name=release_notes::$(cat CHANGELOG.md)"

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: ./artifacts/linux-x64

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: win-x64
          path: ./artifacts/win-x64
