name: Build and Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      

jobs:
  create-artifacts:
    name: Release app
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Print version
        run: echo "{$env.VERSION}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Windows x64
        run: dotnet publish --runtime win-x64 --self-contained true -o ./bin/Realase/${{ github.ref_name }}/EaseeOnboard-${{ github.ref_name }}-win-x64 -c Release -p:DebugType=None -p:DebugSymbols=false -p:PublishSingleFile=true
      - name: Publish Linux x64
        run: dotnet publish --runtime linux-x64 --self-contained true -o ./bin/Realase/${{ github.ref_name }}/EaseeOnboard-${{ github.ref_name }}-linux-x64 -c Release -p:DebugType=None -p:DebugSymbols=false -p:PublishSingleFile=true
      - name: zip files
        run: zip -r -j EaseeOnboard-${{ github.ref_name }}-win-x64.zip ./bin/Realase/${{ github.ref_name }}/EaseeOnboard-${{ github.ref_name }}-win-x64 && zip -r -j EaseeOnboard-${{ github.ref_name }}-linux-x64.zip ./bin/Realase/${{ github.ref_name }}/EaseeOnboard-${{ github.ref_name }}-linux-x64
      
      - name: "Build Changelog"
        id: build-changelog
        uses: mikepenz/release-changelog-builder-action@v4.0.0-b02

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{steps.build-changelog.outputs.changelog}}

      - name: Upload Release Asset
        id: upload-release-asset-1 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./EaseeOnboard-${{ github.ref_name }}-win-x64.zip
          asset_name: EaseeOnboard-${{ github.ref_name }}-win-x64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset
        id: upload-release-asset-2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} 
          asset_path: ./EaseeOnboard-${{ github.ref_name }}-linux-x64.zip
          asset_name: EaseeOnboard-${{ github.ref_name }}-linux-x64.zip
          asset_content_type: application/zip
