name: Build and Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build and Publish for Windows
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -r win-x64 --self-contained --no-restore -o artifacts/win-x64

      - name: Generate Release Notes
        id: release_notes
        run: |
          npm install -g conventional-changelog-cli
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          echo "::set-output name=release_notes::$(cat CHANGELOG.md)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.release_notes.outputs.release_notes }}

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: win-x64
          path: ./artifacts/win-x64
